const HttpError=require('../utils/http-error');
const map=r=>({id:r.id,eventId:r.jornada_id,firstName:r.primer_nombre,middleName:r.segundo_nombre,lastName:r.apellido_paterno,secondLastName:r.apellido_materno,birthDate:r.fecha_nacimiento,curp:r.curp,callingCode:r.lada,phoneCountry:r.pais_telefono,phone:r.telefono,email:r.correo,transport:r.transporte,imageConsent:r.acepta_uso_imagen,privacyConsent:r.acepta_privacidad,liabilityConsent:r.acepta_deslinde,createdAt:r.creado_en});
const mapEvent=r=>({id:r.id,number:r.numero,name:r.nombre,status:r.estado,openedAt:r.abierto_en,closedAt:r.cerrado_en,createdAt:r.creado_en,registrations:Number(r.registros||0)});
async function create(c,input,meta){const client=await c.connect();try{await client.query('BEGIN');const active=await client.query("SELECT id FROM jornadas_limpieza_playas WHERE estado='abierto' FOR UPDATE");if(!active.rowCount)throw new HttpError(409,'El registro para limpieza de playas se encuentra cerrado.','BEACH_REGISTRATION_CLOSED');const r=await client.query(`INSERT INTO registros_limpieza_playas(jornada_id,primer_nombre,segundo_nombre,apellido_paterno,apellido_materno,fecha_nacimiento,curp,lada,pais_telefono,telefono,correo,transporte,acepta_uso_imagen,acepta_privacidad,acepta_deslinde,version_privacidad,direccion_ip,dispositivo) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,TRUE,TRUE,TRUE,$13,$14,$15) RETURNING *`,[active.rows[0].id,input.primerNombre,input.segundoNombre,input.apellidoPaterno,input.apellidoMaterno,input.fechaNacimiento,input.curp,input.lada,input.paisTelefono,input.telefono,input.email,input.transporte,meta.privacyVersion,meta.ip,meta.userAgent]);await client.query('COMMIT');return map(r.rows[0])}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
async function list(c,eventId){const values=[],where=eventId?'WHERE jornada_id=$1':'';if(eventId)values.push(eventId);return (await c.query(`SELECT * FROM registros_limpieza_playas ${where} ORDER BY creado_en DESC`,values)).rows.map(map)}
async function activeEvent(c){const r=await c.query("SELECT * FROM jornadas_limpieza_playas WHERE estado='abierto' LIMIT 1");return r.rowCount?mapEvent(r.rows[0]):null}
async function listEvents(c){return (await c.query(`SELECT j.*,COUNT(r.id) registros FROM jornadas_limpieza_playas j LEFT JOIN registros_limpieza_playas r ON r.jornada_id=j.id GROUP BY j.id ORDER BY j.numero DESC`)).rows.map(mapEvent)}
async function createEvent(c,name){const client=await c.connect();try{await client.query('BEGIN');await client.query("UPDATE jornadas_limpieza_playas SET estado='cerrado',cerrado_en=CURRENT_TIMESTAMP WHERE estado='abierto'");const next=await client.query('SELECT COALESCE(MAX(numero),0)+1 numero FROM jornadas_limpieza_playas');const number=next.rows[0].numero;const r=await client.query("INSERT INTO jornadas_limpieza_playas(numero,nombre,estado,abierto_en) VALUES($1,$2,'abierto',CURRENT_TIMESTAMP) RETURNING *",[number,name||`${number}.ª limpieza de playas`]);await client.query('COMMIT');return mapEvent(r.rows[0])}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
async function setEventStatus(c,id,status){const client=await c.connect();try{await client.query('BEGIN');if(status==='abierto')await client.query("UPDATE jornadas_limpieza_playas SET estado='cerrado',cerrado_en=CURRENT_TIMESTAMP WHERE estado='abierto' AND id<>$1",[id]);const query=status==='abierto'?"UPDATE jornadas_limpieza_playas SET estado='abierto',abierto_en=CURRENT_TIMESTAMP,cerrado_en=NULL WHERE id=$1 RETURNING *":"UPDATE jornadas_limpieza_playas SET estado='cerrado',cerrado_en=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *";const r=await client.query(query,[id]);if(!r.rowCount)throw new HttpError(404,'Jornada no encontrada.','BEACH_EVENT_NOT_FOUND');await client.query('COMMIT');return mapEvent(r.rows[0])}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
module.exports={create,list,activeEvent,listEvents,createEvent,setEventStatus};
