const mapImage=(r)=>({id:r.id,image:`data:${r.imagen_mime};base64,${r.imagen.toString('base64')}`,principal:r.principal});
const mapCall=(r)=>({id:r.id,title:r.titulo,description:r.descripcion,category:r.categoria,type:r.tipo,externalUrl:r.enlace_externo,active:r.activa,image:`data:${r.imagen_mime};base64,${r.imagen.toString('base64')}`,author:'MICE-LO',createdAt:r.creado_en});
const mapApplication=(r)=>({id:r.id,status:r.estado,appliedAt:r.postulado_en,updatedAt:r.actualizado_en,applicant:r.nombre?`${r.nombre} ${r.apellido_paterno}`:undefined,email:r.correo,whatsapp:r.whatsapp,social:{facebook:r.facebook,instagram:r.instagram,x:r.x,tiktok:r.tiktok,youtube:r.youtube,linkedin:r.linkedin},call:{id:r.convocatoria_id,title:r.titulo,description:r.descripcion,category:r.categoria,image:`data:${r.imagen_mime};base64,${r.imagen.toString('base64')}`}});
async function listPublic(c){return (await c.query('SELECT * FROM convocatorias WHERE activa=TRUE ORDER BY creado_en DESC')).rows.map(mapCall)}
async function listAdmin(c){return (await c.query('SELECT * FROM convocatorias ORDER BY creado_en DESC')).rows.map(mapCall)}
async function findPublicById(c,id){const r=await c.query('SELECT * FROM convocatorias WHERE id=$1 AND activa=TRUE',[id]);if(!r.rows[0])return null;const call=mapCall(r.rows[0]),images=await c.query('SELECT * FROM convocatoria_imagenes WHERE convocatoria_id=$1 ORDER BY orden',[id]);call.gallery=images.rows.map(mapImage);return call}
async function findAdminById(c,id){const r=await c.query('SELECT * FROM convocatorias WHERE id=$1',[id]);if(!r.rows[0])return null;const call=mapCall(r.rows[0]),images=await c.query('SELECT * FROM convocatoria_imagenes WHERE convocatoria_id=$1 ORDER BY orden',[id]);call.gallery=images.rows.map(mapImage);return call}
async function create(c,userId,i,principal,gallery){const external=i.tipo==='externa',r=await c.query(`INSERT INTO convocatorias(creador_id,titulo,descripcion,categoria,tipo,enlace_externo,imagen,imagen_mime,correo,whatsapp,facebook,instagram,x,tiktok,youtube,linkedin) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) RETURNING id`,[userId,i.titulo,i.descripcion,i.categoria,i.tipo,external?i.enlaceExterno:null,principal.buffer,principal.mime]);for(let index=0;index<gallery.length;index+=1){const item=gallery[index];await c.query('INSERT INTO convocatoria_imagenes(convocatoria_id,imagen,imagen_mime,orden,principal) VALUES($1,$2,$3,$4,$5)',[r.rows[0].id,item.buffer,item.mime,index,index===(i.imagenPrincipal||0)])}return findPublicById(c,r.rows[0].id)}
async function remove(c,id){return (await c.query('DELETE FROM convocatorias WHERE id=$1 RETURNING id',[id])).rowCount>0}
async function update(c,id,i,principal,gallery){const external=i.tipo==='externa',r=await c.query(`UPDATE convocatorias SET titulo=$2,descripcion=$3,categoria=$4,tipo=$5,enlace_externo=$6,imagen=$7,imagen_mime=$8,correo=NULL,whatsapp=NULL,facebook=NULL,instagram=NULL,x=NULL,tiktok=NULL,youtube=NULL,linkedin=NULL WHERE id=$1 RETURNING id`,[id,i.titulo,i.descripcion,i.categoria,i.tipo,external?i.enlaceExterno:null,principal.buffer,principal.mime]);if(!r.rowCount)return null;await c.query('DELETE FROM convocatoria_imagenes WHERE convocatoria_id=$1',[id]);for(let index=0;index<gallery.length;index+=1){const item=gallery[index];await c.query('INSERT INTO convocatoria_imagenes(convocatoria_id,imagen,imagen_mime,orden,principal) VALUES($1,$2,$3,$4,$5)',[id,item.buffer,item.mime,index,index===(i.imagenPrincipal||0)])}return findAdminById(c,id)}
async function setActive(c,id,active){const r=await c.query('UPDATE convocatorias SET activa=$2 WHERE id=$1 RETURNING *',[id,active]);return r.rows[0]?mapCall(r.rows[0]):null}
async function apply(c,callId,userId){const call=(await c.query('SELECT tipo,titulo FROM convocatorias WHERE id=$1 AND activa=TRUE',[callId])).rows[0];if(!call)return{missing:true};if(call.tipo!=='interna')return{external:true};const u=(await c.query(`SELECT u.correo_electronico,u.nombre,u.apellido_paterno,ps.* FROM usuarios u LEFT JOIN perfiles_sociales ps ON ps.usuario_id=u.id WHERE u.id=$1`,[userId])).rows[0];const r=await c.query(`INSERT INTO postulaciones_convocatoria(convocatoria_id,usuario_id,correo,whatsapp,facebook,instagram,x,tiktok,youtube,linkedin) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(convocatoria_id,usuario_id) DO NOTHING RETURNING *`,[callId,userId,u.correo_electronico,u.mostrar_whatsapp?u.whatsapp:null,u.mostrar_facebook?u.facebook:null,u.mostrar_instagram?u.instagram:null,u.mostrar_x?u.x:null,u.mostrar_tiktok?u.tiktok:null,u.mostrar_youtube?u.youtube:null,u.mostrar_linkedin?u.linkedin:null]);return {application:r.rows[0],user:u,callTitle:call.titulo}}
const applicationSelect=`SELECT a.*,c.titulo,c.descripcion,c.categoria,c.imagen,c.imagen_mime,u.nombre,u.apellido_paterno FROM postulaciones_convocatoria a JOIN convocatorias c ON c.id=a.convocatoria_id JOIN usuarios u ON u.id=a.usuario_id`;
async function listMine(c,userId){return (await c.query(`${applicationSelect} WHERE a.usuario_id=$1 ORDER BY a.postulado_en DESC`,[userId])).rows.map(mapApplication)}
async function listApplications(c){return (await c.query(`${applicationSelect} ORDER BY a.postulado_en DESC`)).rows.map(mapApplication)}
async function updateStatus(c,id,status){const r=await c.query('UPDATE postulaciones_convocatoria SET estado=$2 WHERE id=$1 RETURNING id',[id,status]);return r.rowCount>0}
async function removeApplication(c,id){return (await c.query('DELETE FROM postulaciones_convocatoria WHERE id=$1 RETURNING id',[id])).rowCount>0}
module.exports={apply,create,findAdminById,findPublicById,listAdmin,listApplications,listMine,listPublic,remove,removeApplication,setActive,update,updateStatus};
