BEGIN;
ALTER TABLE perfiles_sociales ALTER COLUMN instagram TYPE VARCHAR(500), ALTER COLUMN x TYPE VARCHAR(500), ALTER COLUMN tiktok TYPE VARCHAR(500), ALTER COLUMN youtube TYPE VARCHAR(500), ALTER COLUMN linkedin TYPE VARCHAR(500);
COMMIT;
