BEGIN;
ALTER TABLE perfiles_sociales ADD COLUMN IF NOT EXISTS facebook VARCHAR(500), ADD COLUMN IF NOT EXISTS mostrar_facebook BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE postulaciones_convocatoria ADD COLUMN IF NOT EXISTS facebook VARCHAR(500);
COMMIT;
