const express=require('express');
const controller=require('../controllers/call.controller');
const authenticate=require('../middlewares/authenticate');
const authorize=require('../middlewares/authorize');
const validate=require('../middlewares/validate');
const {callSchema,statusSchema,visibilitySchema}=require('../models/call.schemas');
const router=express.Router();
router.get('/',controller.list);
router.get('/mine',authenticate,controller.mine);
router.post('/:callId/apply',authenticate,controller.apply);
router.post('/',authenticate,authorize('administrador'),validate(callSchema),controller.create);
router.delete('/:callId',authenticate,authorize('administrador'),controller.remove);
router.get('/admin/list',authenticate,authorize('administrador'),controller.adminList);
router.get('/admin/applications',authenticate,authorize('administrador'),controller.applications);
router.patch('/admin/applications/:applicationId',authenticate,authorize('administrador'),validate(statusSchema),controller.status);
router.delete('/admin/applications/:applicationId',authenticate,authorize('administrador'),controller.removeApplication);
router.get('/admin/:callId',authenticate,authorize('administrador'),controller.adminGet);
router.put('/admin/:callId',authenticate,authorize('administrador'),validate(callSchema),controller.update);
router.patch('/admin/:callId/visibility',authenticate,authorize('administrador'),validate(visibilitySchema),controller.visibility);
router.get('/:callId',controller.get);
module.exports=router;
