import {useCallback,useEffect,useState} from 'react'
import * as api from '../services/authApi'
import AdminCalls from '../components/AdminCalls'
import AdminCallApplications from '../components/AdminCallApplications'
import AdminCallCategories from '../components/AdminCallCategories'
import AdminCallManagement from '../components/AdminCallManagement'
import AdminBeachRegistrations from '../components/AdminBeachRegistrations'
import AdminBeachAnalytics from '../components/AdminBeachAnalytics'
import AdminCategories from '../components/AdminCategories'
import d from './Dashboard.module.css'
import a from './Administration.module.css'
import ProfilePhoto from '../components/ProfilePhoto'

const tabs=[['overview','Resumen'],['new-call','Nueva convocatoria'],['calls','Convocatorias'],['call-applications','Postulantes'],['call-categories','Categorías de convocatorias'],['beach-registrations','Registro de playas'],['projects','Proyectos'],['categories','Categorías de proyectos'],['users','Usuarios y permisos'],['profile','Mi perfil']]
export default function Administration(){
 const[active,setActive]=useState('overview'),[users,setUsers]=useState([]),[projects,setProjects]=useState([]),[calls,setCalls]=useState([]),[beachTotal,setBeachTotal]=useState(0),[pagination,setPagination]=useState({page:1,total:0,limit:20}),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[evidence,setEvidence]=useState(null),[admin,setAdmin]=useState(null)
 const loadUsers=useCallback(async(query='',page=1)=>{setLoading(true);setError('');try{const r=await api.listUsers({search:query,page});setUsers(r.users);setPagination(r.pagination)}catch(e){if(e.status===401)location.href='/sign-up';else setError(e.message)}finally{setLoading(false)}},[])
 useEffect(()=>{api.getCurrentUser().then(u=>{if(!u||u.tipo!=='administrador')return location.href='/sign-up';setAdmin(u)}).catch(()=>location.href='/sign-up');api.listUsers().then(r=>{setUsers(r.users);setPagination(r.pagination)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));api.listAdminProjects().then(r=>setProjects(r.projects)).catch(e=>setError(e.message));api.listCalls().then(r=>setCalls(r.calls)).catch(e=>setError(e.message));api.listBeachRegistrations().then(r=>setBeachTotal((r.registrations||[]).length)).catch(e=>setError(e.message))},[])
 const role=async(u,tipo)=>{try{const r=await api.changeUserRole(u.id,tipo);setUsers(v=>v.map(x=>x.id===u.id?r.user:x))}catch(e){setError(e.message)}}
 const status=async u=>{try{const r=await api.changeUserStatus(u.id,!u.activo);setUsers(v=>v.map(x=>x.id===u.id?r.user:x))}catch(e){setError(e.message)}}
 const consents=async u=>{try{const r=await api.getUserConsents(u.id);setEvidence({user:u,consents:r.consents})}catch(e){setError(e.message)}}
 const removeProject=async p=>{if(!confirm(`¿Eliminar definitivamente "${p.title}"?`))return;try{await api.deleteProject(p.id);setProjects(v=>v.filter(x=>x.id!==p.id))}catch(e){setError(e.message)}}
 if(!admin)return <main className={d.loading}>Cargando dashboard administrativo…</main>
 const pages=Math.max(Math.ceil(pagination.total/pagination.limit),1)
 return <main className={d.page}>
  <aside className={d.sidebar}><div><p className={d.eyebrow}>Administración</p><h2>Hola, {admin.nombre}</h2><span>{admin.correoElectronico}</span></div><nav>{tabs.map(([id,label])=><button key={id} className={active===id?d.active:''} onClick={()=>setActive(id)}>{label}</button>)}</nav></aside>
  <div className={d.content}>
   {error&&<p className={a.error}>{error}</p>}
   {active==='overview'&&<section className={d.panel}><div className={a.heading}><div><p className={d.eyebrow}>Panel de control</p><h1>Resumen administrativo</h1></div><span>{pagination.total} usuarios</span></div><p>Consulta la actividad general y accede a cada módulo desde el menú.</p><div className={a.stats}><article><span>Convocatorias</span><strong>{calls.length}</strong><small>Publicadas</small></article><article><span>Proyectos</span><strong>{projects.length}</strong><small>Registrados</small></article><article><span>Usuarios</span><strong>{pagination.total}</strong><small>Registrados</small></article><article><span>Playas</span><strong>{beachTotal}</strong><small>Registros de limpieza</small></article><article><span>Donaciones</span><strong>$0</strong><small>Cantidad total</small></article></div><div className={a.managementGrid}><article><div><p>Contenido</p><h2>Convocatorias</h2><span>Crea oportunidades y revisa postulaciones.</span></div><button onClick={()=>setActive('calls')}>Administrar</button></article><article><div><p>Moderación</p><h2>Proyectos</h2><span>Revisa y elimina proyectos publicados.</span></div><button onClick={()=>setActive('projects')}>Administrar</button></article><article><div><p>Actividad</p><h2>Detalles de registro de playas</h2><span>Consulta los registros enviados por la comunidad.</span></div><button type="button" onClick={()=>setActive('beach-analytics')}>Ver registros</button></article><article><div><p>Donaciones</p><h2>Resumen de donativos</h2><span>Consulta el total y los movimientos recibidos.</span></div><button type="button" disabled>Ver donaciones</button></article><article><div><p>Accesos</p><h2>Usuarios</h2><span>Gestiona roles, estados y evidencias.</span></div><button onClick={()=>setActive('users')}>Administrar</button></article></div></section>}
   {active==='beach-analytics'&&<AdminBeachAnalytics onBack={()=>setActive('overview')} onCountChange={setBeachTotal}/>}
   {active==='new-call'&&<section className={d.panel}><p className={d.eyebrow}>Publicación</p><h1>Nueva convocatoria</h1><AdminCalls/></section>}
   {active==='calls'&&<section className={d.panel}><p className={d.eyebrow}>Administración</p><h1>Convocatorias</h1><AdminCallManagement/></section>}
   {active==='call-applications'&&<section className={d.panel}><p className={d.eyebrow}>Convocatorias internas</p><h1>Postulantes</h1><AdminCallApplications/></section>}
   {active==='call-categories'&&<section className={d.panel}><p className={d.eyebrow}>Organización</p><h1>Categorías de convocatorias</h1><AdminCallCategories/></section>}
   {active==='beach-registrations'&&<section className={d.panel}><p className={d.eyebrow}>Participación comunitaria</p><h1>Registros de limpieza de playas</h1><AdminBeachRegistrations/></section>}
   {active==='categories'&&<section className={d.panel}><p className={d.eyebrow}>Organización</p><h1>Categorías</h1><AdminCategories/></section>}
   {active==='profile'&&<section className={d.panel}><p className={d.eyebrow}>Cuenta administrativa</p><h1>Mi perfil</h1><ProfilePhoto user={admin} onChange={setAdmin}/><form className={d.form}><label>Nombre<input value={admin.nombre||''} readOnly/></label><label>Segundo nombre<input value={admin.segundoNombre||''} readOnly placeholder="Sin segundo nombre"/></label><label>Apellido paterno<input value={admin.apellidoPaterno||''} readOnly/></label><label>Apellido materno<input value={admin.apellidoMaterno||''} readOnly placeholder="Sin apellido materno"/></label><label className={d.full}>Correo<input value={admin.correoElectronico||''} readOnly/></label></form></section>}
   {active==='projects'&&<section className={d.panel}><p className={d.eyebrow}>Moderación</p><h1>Proyectos publicados</h1><p>Elimina contenido que no deba permanecer en Chiapas por el Clima.</p><div className={a.projectModeration}>{projects.map(p=><article key={p.id}><img src={p.image} alt=""/><div><strong>{p.title}</strong><span>{p.author} · {p.category}</span></div><button onClick={()=>removeProject(p)}>Eliminar</button></article>)}{!projects.length&&<div className={d.empty}><span>○</span><h2>No hay proyectos publicados</h2></div>}</div></section>}
   {active==='users'&&<section className={d.panel}><p className={d.eyebrow}>Accesos</p><h1>Usuarios y permisos</h1><form className={a.search} onSubmit={e=>{e.preventDefault();loadUsers(search,1)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre o correo"/><button disabled={loading}>Buscar</button></form><div className={a.tableWrap}><table><thead><tr><th>Usuario</th><th>Verificación</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.nombre} {u.apellidoPaterno}</strong><span>{u.correoElectronico}</span></td><td>{u.correoVerificado?'Verificado':'Pendiente'}</td><td><select value={u.tipo} onChange={e=>role(u,e.target.value)} disabled={!u.activo}><option value="usuario">Usuario</option><option value="administrador">Administrador</option></select></td><td><span className={u.activo?a.active:a.inactive}>{u.activo?'Activo':'Inactivo'}</span></td><td><div className={a.actions}><button className={a.action} onClick={()=>status(u)}>{u.activo?'Desactivar':'Activar'}</button><button className={a.action} onClick={()=>consents(u)}>Evidencia</button></div></td></tr>)}</tbody></table></div>{evidence&&<aside className={a.evidence}><div><h2>Aceptaciones de {evidence.user.correoElectronico}</h2><button onClick={()=>setEvidence(null)}>Cerrar</button></div>{evidence.consents.map(c=><article key={c.id}><strong>{c.type==='terminos_uso'?'Términos de uso':'Aviso de privacidad'} · versión {c.version}</strong><span>{new Date(c.acceptedAt).toLocaleString()}</span><a href={c.documentUrl} target="_blank" rel="noreferrer">Ver documento</a></article>)}</aside>}<div className={a.pagination}><button disabled={loading||pagination.page<=1} onClick={()=>loadUsers(search,pagination.page-1)}>Anterior</button><span>Página {pagination.page} de {pages}</span><button disabled={loading||pagination.page>=pages} onClick={()=>loadUsers(search,pagination.page+1)}>Siguiente</button></div></section>}
  </div>
 </main>
}
